name: Integration tests

on:
  push:
    branches:
      - "*"
      - "!sapling-pr-archive-*"

jobs:
  test_integration_linux_x86_64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gcc

      - name: Fetch Buck2
        uses: zadlg/buck2-github-composite-action@v1

      - name: Initialize an empty buck2 project
        run: |
          mkdir example/ && cd example
          buck2 init --git
          mkdir gnumake

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: example/gnumake

      - name: Create the `.buckconfig` file
        working-directory: example/
        run: |
          mv gnumake/.buckconfig .
          sed -i 's/gnumake = ./gnumake = gnumake/g' .buckconfig
          touch .buckroot

      - name: Import `gnumake` symbol in main BUCK file.
        working-directory: example/
        run: |
          echo -ne 'load("@gnumake//gnumake:rules.bzl", "gnumake")' > BUCK

      - name: Compile GNUMake
        working-directory: example/
        run: buck2 build -- @gnumake//gnumake ...
